import type { Canvas } from "@/lib/blocks/schemas";

type ProjectData = {
  name: string;
  description?: string | null;
  stack?: Record<string, unknown> | null;
  canvas: Canvas;
  language: string;
};

export function generateClaudeMd(project: ProjectData): string {
  const l = project.language === "es" ? es : en;
  const out: string[] = [];

  // ─── Header ──────────────────────────────────────────────────
  out.push(`# CLAUDE.md — ${project.name}\n`);
  out.push(`> ${l.autoGenerated}\n`);
  if (project.description) {
    out.push(`## ${l.whatIsThis}\n`);
    out.push(`${project.description}\n`);
  }

  // ─── Stack ───────────────────────────────────────────────────
  if (project.stack && Object.keys(project.stack).length > 0) {
    out.push(`## ${l.stack}\n`);
    out.push(`| ${l.layer} | ${l.technology} |`);
    out.push("|---|---|");
    for (const [key, value] of Object.entries(project.stack)) {
      const display = Array.isArray(value) ? value.join(", ") : String(value);
      out.push(`| ${key} | ${display} |`);
    }
    out.push("");
  }

  // ─── Data Models ─────────────────────────────────────────────
  const dataModels = project.canvas.nodes.filter((n) => n.data.blockType === "DataModel");
  if (dataModels.length > 0) {
    out.push(`## ${l.dataModels}\n`);
    for (const n of dataModels) {
      if (n.data.blockType !== "DataModel") continue;
      out.push(`### ${n.data.name}\n`);
      if (n.data.description) out.push(`${n.data.description}\n`);

      out.push("```");
      for (const f of n.data.fields) {
        const flags: string[] = [];
        if (f.required) flags.push("required");
        if (f.unique) flags.push("unique");
        if (f.default) flags.push(`default: ${f.default}`);
        const flagStr = flags.length > 0 ? ` — ${flags.join(", ")}` : "";
        out.push(`  ${f.name}: ${f.type}${flagStr}`);
      }
      out.push("```\n");

      if (n.data.relations.length > 0) {
        out.push(`${l.relations}:`);
        for (const r of n.data.relations) {
          out.push(`- ${r.type} → \`${r.target}\``);
        }
        out.push("");
      }
    }
  }

  // ─── API Endpoints ───────────────────────────────────────────
  const endpoints = project.canvas.nodes.filter((n) => n.data.blockType === "Endpoint");
  if (endpoints.length > 0) {
    out.push(`## API Endpoints\n`);

    // Group by resource (first path segment after /api/)
    const grouped = new Map<string, typeof endpoints>();
    for (const ep of endpoints) {
      if (ep.data.blockType !== "Endpoint") continue;
      const parts = ep.data.path.split("/").filter(Boolean);
      const resource = parts[1] ?? parts[0] ?? "other";
      if (!grouped.has(resource)) grouped.set(resource, []);
      grouped.get(resource)!.push(ep);
    }

    for (const [resource, eps] of grouped) {
      out.push(`### /${resource}\n`);
      for (const ep of eps) {
        if (ep.data.blockType !== "Endpoint") continue;
        out.push(`#### \`${ep.data.method} ${ep.data.path}\`\n`);
        if (ep.data.description) out.push(`${ep.data.description}\n`);
        out.push(`- **Auth:** ${ep.data.auth}`);
        if (ep.data.requestSchema) out.push(`- **Request:** ${ep.data.requestSchema}`);
        if (ep.data.responseSchema) out.push(`- **Response:** ${ep.data.responseSchema}`);
        out.push("");
      }
    }
  }

  // ─── Views / Pages ───────────────────────────────────────────
  const views = project.canvas.nodes.filter((n) => n.data.blockType === "View");
  if (views.length > 0) {
    out.push(`## ${l.views}\n`);
    out.push(`| ${l.viewName} | ${l.route} | ${l.viewDescription} |`);
    out.push("|---|---|---|");
    for (const n of views) {
      if (n.data.blockType !== "View") continue;
      out.push(`| ${n.data.name} | \`${n.data.route ?? "—"}\` | ${n.data.description ?? ""} |`);
    }
    out.push("");

    // Navigation flow
    const navEdges = project.canvas.edges.filter((e) => e.type === "navigatesTo");
    if (navEdges.length > 0) {
      out.push(`### ${l.navigation}\n`);
      for (const edge of navEdges) {
        const from = project.canvas.nodes.find((n) => n.id === edge.source);
        const to = project.canvas.nodes.find((n) => n.id === edge.target);
        if (from && to) {
          const fromName = "name" in from.data ? from.data.name : from.id;
          const toName = "name" in to.data ? to.data.name : to.id;
          out.push(`- ${fromName} → ${toName}`);
        }
      }
      out.push("");
    }
  }

  // ─── Auth ────────────────────────────────────────────────────
  const auth = project.canvas.nodes.filter((n) => n.data.blockType === "Auth");
  if (auth.length > 0) {
    out.push(`## ${l.auth}\n`);
    for (const n of auth) {
      if (n.data.blockType !== "Auth") continue;
      out.push(`- **${l.method}:** ${n.data.method}`);
      out.push(`- **${l.roles}:** ${n.data.roles.join(", ")}`);

      // Find what this auth protects
      const protectsEdges = project.canvas.edges.filter(
        (e) => e.source === n.id && e.type === "protects",
      );
      if (protectsEdges.length > 0) {
        out.push(`- **${l.protects}:**`);
        for (const e of protectsEdges) {
          const target = project.canvas.nodes.find((nd) => nd.id === e.target);
          if (target) {
            const name =
              "name" in target.data
                ? target.data.name
                : "path" in target.data
                  ? target.data.path
                  : target.id;
            out.push(`  - ${target.type}: ${name}`);
          }
        }
      }
      out.push("");
    }
  }

  // ─── Integrations ────────────────────────────────────────────
  const integrations = project.canvas.nodes.filter((n) => n.data.blockType === "Integration");
  if (integrations.length > 0) {
    out.push(`## ${l.integrations}\n`);
    for (const n of integrations) {
      if (n.data.blockType !== "Integration") continue;
      out.push(`### ${n.data.service}\n`);
      out.push(`${n.data.purpose}\n`);
      if (n.data.secretsNeeded.length > 0) {
        out.push(`**${l.envVars}:**`);
        for (const s of n.data.secretsNeeded) {
          out.push(`- \`${s}\``);
        }
      }
      out.push("");
    }
  }

  // ─── Jobs ────────────────────────────────────────────────────
  const jobs = project.canvas.nodes.filter((n) => n.data.blockType === "Job");
  if (jobs.length > 0) {
    out.push(`## ${l.jobs}\n`);
    for (const n of jobs) {
      if (n.data.blockType !== "Job") continue;
      out.push(`### ${n.data.name}\n`);
      out.push(
        `- **${l.trigger}:** ${n.data.trigger}${n.data.frequency ? ` (${n.data.frequency})` : ""}`,
      );
      out.push(`- **${l.action}:** ${n.data.action}`);
      out.push("");
    }
  }

  // ─── User Flows ──────────────────────────────────────────────
  const flows = project.canvas.nodes.filter((n) => n.data.blockType === "UserFlow");
  if (flows.length > 0) {
    out.push(`## ${l.userFlows}\n`);
    for (const n of flows) {
      if (n.data.blockType !== "UserFlow") continue;
      out.push(`### ${n.data.name}\n`);
      n.data.steps.forEach((step, i) => {
        out.push(
          `${i + 1}. **${step.actor}** — ${step.action}${step.target ? ` → \`${step.target}\`` : ""}`,
        );
      });
      out.push("");
    }
  }

  // ─── Environment Variables Summary ───────────────────────────
  const allSecrets = new Set<string>();
  for (const n of project.canvas.nodes) {
    if (n.data.blockType === "Integration") {
      for (const s of n.data.secretsNeeded) {
        allSecrets.add(s);
      }
    }
  }
  if (allSecrets.size > 0) {
    out.push(`## ${l.envVarsSummary}\n`);
    out.push("```bash");
    for (const s of allSecrets) {
      out.push(`${s}=`);
    }
    out.push("```\n");
  }

  // ─── Architecture Notes ──────────────────────────────────────
  const notes = project.canvas.nodes.filter((n) => n.data.blockType === "Note");
  if (notes.length > 0) {
    out.push(`## ${l.notes}\n`);
    for (const n of notes) {
      if (n.data.blockType !== "Note") continue;
      out.push(`${n.data.content}\n`);
    }
  }

  // ─── Footer ──────────────────────────────────────────────────
  out.push("---");
  out.push(`*${l.footer}*\n`);

  return out.join("\n");
}

// ─── i18n strings ──────────────────────────────────────────────

const en = {
  autoGenerated:
    "Auto-generated by Architext. Place this file in your project root so AI coding assistants understand your architecture.",
  whatIsThis: "What is this project",
  stack: "Tech Stack",
  layer: "Layer",
  technology: "Technology",
  dataModels: "Data Models",
  relations: "Relations",
  views: "Views & Pages",
  viewName: "Page",
  route: "Route",
  viewDescription: "Description",
  navigation: "Navigation Flow",
  auth: "Authentication & Authorization",
  method: "Method",
  roles: "Roles",
  protects: "Protects",
  integrations: "External Integrations",
  envVars: "Required environment variables",
  envVarsSummary: "All Environment Variables",
  jobs: "Background Jobs",
  trigger: "Trigger",
  action: "Action",
  userFlows: "User Flows",
  notes: "Architecture Notes",
  footer: "Generated by Architext — https://github.com/DelvyG/Architext",
};

const es: typeof en = {
  autoGenerated:
    "Auto-generado por Architext. Coloca este archivo en la raíz de tu proyecto para que los asistentes de IA entiendan tu arquitectura.",
  whatIsThis: "De qué trata este proyecto",
  stack: "Stack tecnológico",
  layer: "Capa",
  technology: "Tecnología",
  dataModels: "Modelos de datos",
  relations: "Relaciones",
  views: "Vistas y páginas",
  viewName: "Página",
  route: "Ruta",
  viewDescription: "Descripción",
  navigation: "Flujo de navegación",
  auth: "Autenticación y autorización",
  method: "Método",
  roles: "Roles",
  protects: "Protege",
  integrations: "Integraciones externas",
  envVars: "Variables de entorno requeridas",
  envVarsSummary: "Todas las variables de entorno",
  jobs: "Trabajos en segundo plano",
  trigger: "Disparador",
  action: "Acción",
  userFlows: "Flujos de usuario",
  notes: "Notas de arquitectura",
  footer: "Generado por Architext — https://github.com/DelvyG/Architext",
};
