import type { Canvas } from "@/lib/blocks/schemas";

type ProjectData = {
  name: string;
  description?: string | null;
  stack?: Record<string, unknown> | null;
  canvas: Canvas;
  language: string;
};

export function generatePrd(project: ProjectData): string {
  const out: string[] = [];

  const dataModels = project.canvas.nodes.filter((n) => n.data.blockType === "DataModel");
  const endpoints = project.canvas.nodes.filter((n) => n.data.blockType === "Endpoint");
  const views = project.canvas.nodes.filter((n) => n.data.blockType === "View");
  const integrations = project.canvas.nodes.filter((n) => n.data.blockType === "Integration");
  const flows = project.canvas.nodes.filter((n) => n.data.blockType === "UserFlow");
  const auth = project.canvas.nodes.filter((n) => n.data.blockType === "Auth");
  const jobs = project.canvas.nodes.filter((n) => n.data.blockType === "Job");

  // ─── Title ───────────────────────────────────────────────────
  out.push(`# PRD — ${project.name}\n`);
  out.push(`> Generated by Architext\n`);

  // ─── Executive Summary ───────────────────────────────────────
  out.push("## 1. Executive Summary\n");
  out.push(project.description || "No description provided.");
  out.push("");
  out.push(
    `The system comprises ${dataModels.length} data models, ${endpoints.length} API endpoints, ${views.length} user-facing pages, and ${integrations.length} external integrations.\n`,
  );

  // ─── Stack ───────────────────────────────────────────────────
  if (project.stack && Object.keys(project.stack).length > 0) {
    out.push("## 2. Technical Stack\n");
    out.push("| Layer | Technology |");
    out.push("|---|---|");
    for (const [key, value] of Object.entries(project.stack)) {
      out.push(`| ${key} | ${Array.isArray(value) ? value.join(", ") : String(value)} |`);
    }
    out.push("");
  }

  // ─── Data Architecture ───────────────────────────────────────
  if (dataModels.length > 0) {
    out.push("## 3. Data Architecture\n");
    for (const n of dataModels) {
      if (n.data.blockType !== "DataModel") continue;
      out.push(`### ${n.data.name}\n`);
      if (n.data.description) out.push(`${n.data.description}\n`);
      out.push(`**Fields:** ${n.data.fields.length} | **Relations:** ${n.data.relations.length}\n`);
      out.push("| Field | Type | Required | Constraints |");
      out.push("|---|---|---|---|");
      for (const f of n.data.fields) {
        const constraints: string[] = [];
        if (f.unique) constraints.push("unique");
        if (f.default) constraints.push(`default: ${f.default}`);
        out.push(
          `| ${f.name} | ${f.type} | ${f.required ? "Yes" : "No"} | ${constraints.join(", ") || "—"} |`,
        );
      }
      out.push("");
    }
  }

  // ─── API Surface ─────────────────────────────────────────────
  if (endpoints.length > 0) {
    out.push("## 4. API Surface\n");
    out.push("| Method | Endpoint | Auth | Description |");
    out.push("|---|---|---|---|");
    for (const n of endpoints) {
      if (n.data.blockType !== "Endpoint") continue;
      out.push(
        `| ${n.data.method} | \`${n.data.path}\` | ${n.data.auth} | ${n.data.description ?? "—"} |`,
      );
    }
    out.push("");
  }

  // ─── User Interface ──────────────────────────────────────────
  if (views.length > 0) {
    out.push("## 5. User Interface\n");
    for (const n of views) {
      if (n.data.blockType !== "View") continue;
      out.push(`### ${n.data.name}\n`);
      if (n.data.route) out.push(`**Route:** \`${n.data.route}\`\n`);
      if (n.data.description) out.push(`${n.data.description}\n`);
    }
  }

  // ─── Auth & Security ─────────────────────────────────────────
  if (auth.length > 0) {
    out.push("## 6. Authentication & Security\n");
    for (const n of auth) {
      if (n.data.blockType !== "Auth") continue;
      out.push(`- **Method:** ${n.data.method}`);
      out.push(`- **Roles:** ${n.data.roles.join(", ")}\n`);
    }
    const protectedEndpoints = endpoints.filter(
      (ep) => ep.data.blockType === "Endpoint" && ep.data.auth !== "none",
    );
    if (protectedEndpoints.length > 0) {
      out.push(
        `${protectedEndpoints.length} of ${endpoints.length} endpoints require authentication.\n`,
      );
    }
  }

  // ─── Integrations ────────────────────────────────────────────
  if (integrations.length > 0) {
    out.push("## 7. External Integrations\n");
    out.push("| Service | Purpose | Required Secrets |");
    out.push("|---|---|---|");
    for (const n of integrations) {
      if (n.data.blockType !== "Integration") continue;
      out.push(
        `| ${n.data.service} | ${n.data.purpose} | ${n.data.secretsNeeded.join(", ") || "—"} |`,
      );
    }
    out.push("");
  }

  // ─── User Flows ──────────────────────────────────────────────
  if (flows.length > 0) {
    out.push("## 8. User Flows\n");
    for (const n of flows) {
      if (n.data.blockType !== "UserFlow") continue;
      const flowData = n.data;
      out.push(`### ${flowData.name}\n`);
      out.push("```mermaid");
      out.push("graph TD");
      flowData.steps.forEach((step, i) => {
        const id = `S${i}`;
        const nextId = `S${i + 1}`;
        out.push(`  ${id}["${step.actor}: ${step.action}"]`);
        if (i < flowData.steps.length - 1) {
          out.push(`  ${id} --> ${nextId}`);
        }
      });
      out.push("```\n");
    }
  }

  // ─── Jobs ────────────────────────────────────────────────────
  if (jobs.length > 0) {
    out.push("## 9. Background Processes\n");
    out.push("| Job | Trigger | Description |");
    out.push("|---|---|---|");
    for (const n of jobs) {
      if (n.data.blockType !== "Job") continue;
      const trigger = `${n.data.trigger}${n.data.frequency ? ` (${n.data.frequency})` : ""}`;
      out.push(`| ${n.data.name} | ${trigger} | ${n.data.action} |`);
    }
    out.push("");
  }

  // ─── Scope Summary ──────────────────────────────────────────
  out.push("## Scope Summary\n");
  out.push(`- **${dataModels.length}** data models`);
  out.push(`- **${endpoints.length}** API endpoints`);
  out.push(`- **${views.length}** pages/views`);
  out.push(`- **${integrations.length}** external integrations`);
  out.push(`- **${jobs.length}** background jobs`);
  out.push(`- **${flows.length}** documented user flows`);
  out.push(`- **${project.canvas.edges.length}** architecture connections\n`);

  out.push("---");
  out.push("*Generated by Architext*\n");

  return out.join("\n");
}
