import type { Canvas } from "@/lib/blocks/schemas";

const TYPE_MAP: Record<string, string> = {
  string: "VARCHAR(255)",
  text: "TEXT",
  integer: "INTEGER",
  int: "INTEGER",
  float: "FLOAT",
  boolean: "BOOLEAN",
  datetime: "TIMESTAMP",
  date: "DATE",
  json: "JSONB",
  uuid: "UUID",
  email: "VARCHAR(255)",
};

export function generateSqlSchema(canvas: Canvas): string {
  const lines: string[] = [];
  lines.push("-- Generated by Architext");
  lines.push("-- Target: PostgreSQL\n");

  const dataModels = canvas.nodes.filter((n) => n.data.blockType === "DataModel");

  for (const n of dataModels) {
    if (n.data.blockType !== "DataModel") continue;

    const tableName = n.data.name
      .replace(/([A-Z])/g, "_$1")
      .toLowerCase()
      .replace(/^_/, "");
    lines.push(`CREATE TABLE ${tableName} (`);

    const fieldLines: string[] = [];
    for (const field of n.data.fields) {
      const sqlType = TYPE_MAP[field.type.toLowerCase()] ?? "VARCHAR(255)";
      let line = `  ${field.name} ${sqlType}`;
      if (field.required) line += " NOT NULL";
      if (field.unique) line += " UNIQUE";
      if (field.default) line += ` DEFAULT ${field.default}`;
      fieldLines.push(line);
    }

    // Add timestamps
    fieldLines.push("  created_at TIMESTAMP NOT NULL DEFAULT NOW()");
    fieldLines.push("  updated_at TIMESTAMP NOT NULL DEFAULT NOW()");

    lines.push(fieldLines.join(",\n"));
    lines.push(");\n");

    // Add relations as foreign keys
    for (const rel of n.data.relations) {
      const targetTable = rel.target
        .replace(/([A-Z])/g, "_$1")
        .toLowerCase()
        .replace(/^_/, "");
      lines.push(
        `ALTER TABLE ${tableName} ADD COLUMN ${targetTable}_id UUID REFERENCES ${targetTable}(id);`,
      );
    }
    if (n.data.relations.length > 0) lines.push("");
  }

  return lines.join("\n");
}
