import type { Canvas } from "@/lib/blocks/schemas";

const TYPE_MAP: Record<string, string> = {
  string: "VARCHAR(255)",
  text: "TEXT",
  integer: "INTEGER",
  int: "INTEGER",
  float: "DOUBLE PRECISION",
  decimal: "DECIMAL(10,2)",
  boolean: "BOOLEAN",
  datetime: "TIMESTAMPTZ",
  timestamp: "TIMESTAMPTZ",
  date: "DATE",
  json: "JSONB",
  uuid: "UUID",
  email: "VARCHAR(255)",
  enum: "VARCHAR(50)",
};

function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "")
    .replace(/__+/g, "_");
}

function mapType(typeStr: string): string {
  const lower = typeStr.toLowerCase();
  if (lower.startsWith("enum(") || lower.startsWith("enum (")) {
    return "VARCHAR(50)";
  }
  return TYPE_MAP[lower] ?? "VARCHAR(255)";
}

export function generateSqlSchema(canvas: Canvas): string {
  const out: string[] = [];
  out.push("-- =============================================");
  out.push("-- Generated by Architext");
  out.push("-- Target: PostgreSQL 16+");
  out.push("-- =============================================\n");

  const dataModels = canvas.nodes.filter((n) => n.data.blockType === "DataModel");

  if (dataModels.length === 0) {
    out.push("-- No data models defined yet.");
    return out.join("\n");
  }

  for (const n of dataModels) {
    if (n.data.blockType !== "DataModel") continue;

    const tableName = toSnakeCase(n.data.name) + "s";

    if (n.data.description) {
      out.push(`-- ${n.data.description}`);
    }
    out.push(`CREATE TABLE ${tableName} (`);

    const lines: string[] = [];

    for (const field of n.data.fields) {
      const colName = toSnakeCase(field.name);
      const sqlType = mapType(field.type);

      if (colName === "id") {
        if (field.type.toLowerCase() === "uuid") {
          lines.push(`  ${colName} UUID PRIMARY KEY DEFAULT gen_random_uuid()`);
        } else {
          lines.push(`  ${colName} ${sqlType} PRIMARY KEY`);
        }
        continue;
      }

      let line = `  ${colName} ${sqlType}`;
      if (field.required) line += " NOT NULL";
      if (field.unique) line += " UNIQUE";
      if (field.default) {
        const def = field.default.toLowerCase();
        if (def === "now()" || def === "current_timestamp") {
          line += " DEFAULT NOW()";
        } else if (def === "true" || def === "false") {
          line += ` DEFAULT ${def.toUpperCase()}`;
        } else if (/^\d+$/.test(def)) {
          line += ` DEFAULT ${def}`;
        } else {
          line += ` DEFAULT '${field.default}'`;
        }
      }
      lines.push(line);
    }

    const fieldNames = n.data.fields.map((f) => toSnakeCase(f.name));
    if (!fieldNames.includes("created_at") && !fieldNames.includes("createdat")) {
      lines.push("  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()");
    }
    if (!fieldNames.includes("updated_at") && !fieldNames.includes("updatedat")) {
      lines.push("  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()");
    }

    out.push(lines.join(",\n"));
    out.push(");\n");

    for (const rel of n.data.relations) {
      const targetTable = toSnakeCase(rel.target) + "s";
      const fkCol = toSnakeCase(rel.target) + "_id";
      if (!fieldNames.includes(fkCol)) {
        out.push(
          `ALTER TABLE ${tableName} ADD COLUMN ${fkCol} UUID REFERENCES ${targetTable}(id);`,
        );
      }
    }

    const fkFields = n.data.fields.filter((f) => f.name.endsWith("Id") || f.name.endsWith("_id"));
    for (const fk of fkFields) {
      const colName = toSnakeCase(fk.name);
      out.push(`CREATE INDEX idx_${tableName}_${colName} ON ${tableName}(${colName});`);
    }

    if (fkFields.length > 0 || n.data.relations.length > 0) {
      out.push("");
    }
  }

  out.push("-- Auto-update updated_at on row changes");
  out.push("CREATE OR REPLACE FUNCTION update_updated_at()");
  out.push("RETURNS TRIGGER AS $$");
  out.push("BEGIN");
  out.push("  NEW.updated_at = NOW();");
  out.push("  RETURN NEW;");
  out.push("END;");
  out.push("$$ LANGUAGE plpgsql;\n");

  for (const n of dataModels) {
    if (n.data.blockType !== "DataModel") continue;
    const tableName = toSnakeCase(n.data.name) + "s";
    out.push(`CREATE TRIGGER trg_${tableName}_updated_at`);
    out.push(`  BEFORE UPDATE ON ${tableName}`);
    out.push(`  FOR EACH ROW EXECUTE FUNCTION update_updated_at();`);
  }
  out.push("");

  return out.join("\n");
}
